/*
 * generated by Xtext 2.16.0
 */
package org.butterflylabs.zilliqa.xtext.tests

import com.google.inject.Inject
import org.butterflylabs.zilliqa.xtext.scilla.Scilla
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(ScillaInjectorProvider)
class ScillaParsingTest {
	@Inject
	ParseHelper<Scilla> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			import BoolUtils
			library test
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
