/*
 * generated by Xtext 2.16.0
 */
package org.butterflylabs.zilliqa.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ScillaStandaloneSetup extends ScillaStandaloneSetupGenerated {

	def static void doSetup() {
		new ScillaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
